{{- if .Values.externalSecret.create -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "universal-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}

spec:
  # Optional, SecretStoreRef defines the default SecretStore to use when fetching the secret data.
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}

  # RefreshInterval is the amount of time before the values reading again from the SecretStore provider
  # Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h" (from time.ParseDuration)
  # May be set to zero to fetch and create it once
  refreshInterval: "1h"

  # the target describes the secret that shall be created
  # there can only be one target per ExternalSecret
  target:
    creationPolicy: Owner
    template:
      type: Opaque

      {{- if .Values.externalSecret.useTemplateEngine }}
      data:
        {{- range .Values.externalSecret.mappings }}
        {{- if .templateString }}
        {{ .secretKey }}: |-
          {{- .templateString | nindent 10 }}
        {{- else }}
        {{ .secretKey }}: {{ printf "'{{ .%s | toString }}'" .secretKey }}
        {{- end }}
        {{- end }}
      {{- end }}

  {{- if .Values.externalSecret.useTemplateEngine }}
  data:
    {{- range .Values.externalSecret.mappings }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        {{- if .remoteRef.property }}
        property: {{ .remoteRef.property }}
        {{- end }}
        {{- if .remoteRef.decodingStrategy }}
        decodingStrategy: {{ .remoteRef.decodingStrategy }}
        {{- end }}
    {{- end }}
  {{- else }}
  dataFrom:
  - extract:
      key: {{ include "universal-chart.fullname" . }}
      decodingStrategy: {{ .Values.externalSecret.decodingStrategy }}
  {{- end }}

{{- end -}}
