{{- if .Values.persistentVolumeClaim.create -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "universal-chart.pvcName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.size }}
  storageClassName: {{ .Values.persistentVolumeClaim.storageClassName }}
{{- end }}
