apiVersion: v2
appVersion: 0.3.0
description: Helm Chart for the leoligz-org
home: https://github.com/leoligz-org/reusable-workflows
keywords:
- kubernetes
maintainers:
- email: leoligz@yahoo.com
  name: Leo Li
- email: andrew.li2252@gmail.com
  name: Andrew Li
name: universal
version: 0.3.0
