name: Build and Release Docker Images

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*'           # Push events to every tag not containing /

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    # Optional: Provide a description for the manual trigger UI
    inputs:
      ghcr:
        description: 'Whether to push to GHCR after build'
        required: true
        default: true
        type: boolean
      private:
        description: 'Whether to push to private registry after build'
        required: true
        default: true
        type: boolean

env:
  IMAGE_NAME: ${{ vars.IMAGE_REGISTRY }}/${{ vars.IMAGE_REPOSITORY }}

jobs:
  build:
    runs-on: [arc-runners-org] # our new runner set
    container:
      image: gcr.io/kaniko-project/executor:debug # the kaniko image
    permissions:
      contents: read # read the repository
      packages: write # push to GHCR, omit if not pushing to GitHub's container registry

    outputs:
      image_name_tag_digest: ${{ steps.build.outputs.image_name_tag_digest }}
    steps:
      - name: Build and push container to GHCR and/or private registry
        id: build
        shell: bash
        run: |
          auth_entries=()
          dest_entries=()
          if ${{ inputs.ghcr }}; then
            AUTH_GHCR=$(echo -n '${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}' | base64)
            auth_entries+=("\"ghcr.io\": {\"auth\": \"${AUTH_GHCR}\"}")
            dest_entries+=("ghcr.io/${GITHUB_REPOSITORY}/${{ vars.IMAGE_REPOSITORY }}:${{ github.ref_name }}")
          fi
          if ${{ inputs.private }}; then
            AUTH_PRIVATE=$(echo -n '${{ secrets.REGISTRY_SA }}:${{ secrets.REGISTRY_PASS }}' | base64)
            auth_entries+=("\"$(dirname ${{ vars.IMAGE_REGISTRY }})\": {\"auth\": \"${AUTH_PRIVATE}\"}")
            dest_entries+=("${{ env.IMAGE_NAME }}:${{ github.ref_name }}")
          fi
          auth_string=$(IFS=,; echo "${auth_entries[*]}")
          echo "{\"auths\": {${auth_string}}}" > /kaniko/.docker/config.json

          # Configure git
          export GIT_USERNAME="kaniko-bot"
          export GIT_PASSWORD="${{ secrets.GITHUB_TOKEN }}" # works for GHEC or GHES container registry

          # Build and push (sub in your image, of course)
          dest_args=$(printf "--destination=%s " "${dest_entries[@]}")
          /kaniko/executor --dockerfile="Dockerfile" \
            --context="${{ github.repositoryUrl }}#${{ github.ref }}#${{ github.sha }}" \
            ${dest_args[@]} \
            --push-retry 5 \
            --image-name-tag-with-digest-file /workspace/image-digest.txt
          echo "image_name_tag_digest=$(cat /workspace/image-digest.txt)" >> "$GITHUB_OUTPUT"

  sign:
    if: inputs.private
    runs-on: [arc-runners-org]
    needs: build
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v6

      - uses: ./.github/actions/cache

      - name: Cosign image signing
        env:
          image_name_tag_digest: ${{ needs.build.outputs.image_name_tag_digest }}
        run: |
          /home/runner/bin/cosign login $(dirname ${{ vars.IMAGE_REGISTRY }}) -u '${{ secrets.REGISTRY_SA }}' -p '${{ secrets.REGISTRY_PASS }}'
          /home/runner/bin/cosign sign --key k8s://arc-runners/cosign ${image_name_tag_digest}

      - name: Cosign image signing verifying
        env:
          image_name_tag_digest: ${{ needs.build.outputs.image_name_tag_digest }}
        run: |
          /home/runner/bin/cosign verify --key k8s://arc-runners/cosign ${image_name_tag_digest}
